### PR TITLE
[BAD-220] - Extend BD functionality to S3

### PR DESCRIPTION
**Pull request by stepanovdg**
* Updated jets3t version
* Fixed recursive delete and creation

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mattyb149  Could you please take a look?

**Comment by mattyb149** [comment]
This should really have unit tests and be free of Checkstyle violations. If @mbradbury2014 gets clearance from Bob I will merge this with the promise that a cleanup/test commit is coming soon :)

**Comment by bkemper-pentaho** [comment]
Nope - needs check style and unit tests....

Plus - has the new library gone through the component process before we introduce it to the build?




Bob Kemper
Executive Vice President of Engineering
[cid:D7F72B00-65DC-4890-A40B-85C908E8C8AA]

5950 Hazeltine National Dr.
Suite 340
Orlando, FL 32822
(407)-965-4019

**Comment by stepanovdg** [comment]
@mattyb149  pull-request updated :
included checkstyle and unit test.
There is problem with test running with real s3 credentials - they crashes periodically. More over sometimes these test hangs forever (15 -20 min was waited - without any result). But when was tried to run tests in debug mode - they succeeded. May be reason relates to some race conditions (due to slow transport layer). But still these tests proceed failing without my changes - so this is not regression.

**Pull request merged**
