### PR TITLE
[BACKLOG-29332] S3 Multipart Upload does not allow configurable part …

### PR DESCRIPTION
**Pull request by NJtwentyone**
…sizes

- created/use kettle property 's3.vfs.partSize'

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by NJtwentyone** [comment]
this PR https://github.com/pentaho/jenkins-pipelines/pull/442 needs to be merged before this will be succesful. penatho-s3-vfs will be added to after kettle core/engine but before pentaho-big-data -P lowdeps

**Comment by NJtwentyone** [comment]
failed test "org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.mqttReadsBinary" is unrelated. reason
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

**Comment by NJtwentyone** [comment]
https://jira.pentaho.com/browse/BACKLOG-33640 is now a blocker.

**Pull request closed without merging**
