### PR TITLE
[BACKLOG-29332] S3 Multipart Upload does not allow configurable part …

### PR DESCRIPTION
**Pull request by NJtwentyone**
…sizes

- created/use kettle property 's3.vfs.partSize'

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by NJtwentyone** [comment]
build is failing due to dependency on new class created in https://github.com/pentaho/pentaho-kettle/pull/7335

**Comment by buildguy** [comment]
### :warning: Build finished in 1m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.s3.vfs.S3FileObjectTest.testDoGetOutputStream</b> (click to expand)</summary><p>

```
Central Log Store is not initialized!!!
```

</p></details>

  
Tests run: **49**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/s3-vfs/job/PR-95/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by NJtwentyone** [comment]
jenkins build order needs to be updated before this can be merge + a test is failing.

**Pull request closed without merging**
