### PR TITLE
[PDI-13700] - S3 File Output Fails when writing to large buckets

### PR DESCRIPTION
**Pull request by stepanovdg**
* Added handles for create and deletion which invalidate filecache - the reason for test failing
* Changed the way of determining object`s type  - do not cache all children  - so TextFileOutput step into s3 is working  and not failing with OOM exception. But still if we try to load all children using function listChildren (for example with the help of some browse dialog) - we will fail with OOM. Most of all it is related but not the same bug and for its fixing need to change both logic of our VFS browser implementation (provide paging and try to load children in chunks) and  architecture of S3vfs (try to find the way to decrease memory needed for one object)

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mattyb149 @brosander Could you please take a look ?

**Comment by kcruzada** [comment]
@mattyb149 @brosander @mbradbury2014 can you have this pull request processed?

**Comment by mattyb149** [comment]
All unit tests fail for me, is there something I need to set up?

**Comment by stepanovdg** [comment]
You need to create properties file which contains real amazon s3 access key and secret key.

**Comment by mattyb149** [comment]
Is this documented somewhere? Can we add a dummy one with comments that say "replace me with X"?

**Comment by stepanovdg** [comment]
Done: added properties file with placeholders.

**Comment by mtseu** [comment]
@mattyb149 why have the request been closed? is there something wrong?

**Pull request closed without merging**
